# =============================================================================
# CI Pipeline - Build and Push
# =============================================================================
# 
# This is intentionally simple:
#   1. Lint & type check
#   2. Build Docker image
#   3. Push to registry
#
# Deployment is handled automatically by Watchtower on the server.
# No SSH, no complex scripts - just push and go.
# =============================================================================

name: Build
run-name: "Build: ${{ gitea.ref_name }} by ${{ gitea.actor }}"

on:
  push:
    branches: [web]
  pull_request:
    branches: [web]

env:
  REGISTRY: gitea.intranet.advancedyapping.be
  IMAGE_NAME: ${{ gitea.repository }}

jobs:
  # ===========================================================================
  # Quality Checks
  # ===========================================================================
  check:
    name: Lint & Type Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"
          cache-dependency-path: web/pnpm-lock.yaml

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint & Type Check
        run: |
          pnpm check
          pnpm exec tsc --noEmit

  # ===========================================================================
  # Build & Push Image
  # ===========================================================================
  build:
    name: Build & Push
    runs-on: ubuntu-latest
    needs: check
    if: gitea.event_name == 'push'
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: ./web
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ gitea.sha }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cache,mode=max
          provenance: false
