name: Build and Deploy
run-name: Deploying ${{ gitea.actor }}'s changes

on:
  push:
    branches:
      - web

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Gitea Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ gitea.server_url }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ gitea.server_url }}/${{ gitea.repository }}
          tags: type=raw,value=latest

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: ./web
          file: ./web/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Navigate to the folder in your home directory
            cd ~/reseau

            # Log into registry (using sudo if needed)
            echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login ${{ gitea.server_url }} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

            # Calculate lowercase image URL
            IMAGE_URL=$(echo "${{ gitea.server_url }}/${{ gitea.repository }}:latest" | tr '[:upper:]' '[:lower:]')

            # Pull new image
            sudo docker pull $IMAGE_URL

            # Restart app only
            sudo docker compose up -d --no-deps app

            # Cleanup
            sudo docker image prune -f